# Generated by Django 4.1.4 on 2022-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.IntegerField(unique=True)),
                ("emergency_contact_name", models.CharField(max_length=80)),
                ("emergency_contact_phone_number", models.IntegerField()),
                ("symptoms", models.TextField(max_length=500)),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField()),
            ],
        ),
    ]
