# Generated by Django 4.1.4 on 2022-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdetail",
            name="preferred_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="patientdetail",
            name="preferred_time",
            field=models.CharField(max_length=20),
        ),
    ]
