# Generated by Django 4.1.4 on 2022-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_patientdetail_preferred_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdetail",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
