# Generated by Django 4.1.4 on 2022-12-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_patientdetail_diagnosis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdetail",
            name="symptoms",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
