# Generated by Django 4.1.4 on 2022-12-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_alter_patientdetail_symptoms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdetail",
            name="preferred_date",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
