# Generated by Django 4.1.4 on 2022-12-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_alter_patientdetail_preferred_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientdetail",
            old_name="preferred_time",
            new_name="preferred_date_and_time",
        ),
        migrations.RemoveField(
            model_name="patientdetail",
            name="preferred_date",
        ),
    ]
