# Generated by Django 4.1.4 on 2022-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_health_worker",
            field=models.BooleanField(default=False, verbose_name="health worker"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_patient",
            field=models.BooleanField(default=False, verbose_name="patient"),
        ),
    ]
